#ifndef TEMPLATES

const char HTTP_HEAD[] PROGMEM = "<!DOCTYPE html><html lang=\"en\"><head><meta http-equiv=\"refresh\" content=\"30\" name=\"viewport\" content=\"width:device-width, initial-scale=1, user-scalable=no\" /><title>Oneino</title>";

const char HTTP_STYLE[] PROGMEM = "<style>div,input{padding:5px;margin:10px;font-size:1em;}body{text-align: center;font-family:georgia;}button{border:0;border-radius:0.3rem;background-color:#010012;color:#ffffff;line-height:2.4rem;font-size:1.2rem;width:100%;box-shadow: 0 9px #999;}button:active{box-shadow: 0 5px #666;transform: translateY(4px);}</style>";

const char HTTP_SCRIPT[] PROGMEM = "<script>function copyIt(txt){document.getElementById(\"ssid\").value = txt.innerHTML; }</script>";

const char HTTP_HEAD_END[] PROGMEM = "</head>";

const char WIFI_MAN_SCAN[] PROGMEM = "<body><div style=\"text-align:left;display:inline-block;min-width:260px;\"><form action=\"/handleConfig\" method=\"POST\"><h4 style=\"text-align: center;\">SSID:</h4><input type=\"password\" class=\"input_type\" name=\"stassid\" minlength=\"4\" maxlength=\"32\" placeholder=\"SSID\" autofocus required><br><br><h4 style=\"text-align: center;\">Password:</h4><input type=\"password\" class=\"input_type\" name=\"stapass\" minlength=\"8\" maxlength=\"16\" placeholder=\"Password\" required><br><br><input type=\"submit\" style=\"border:0;border-radius:0.3rem;background-color:#010012;color:#fff;line-height:2.4rem;font-size:1.2rem;width:100%;\" name=\"Submit\" value=\"Submit\"></form></div></body></html>";

const char AP_CONFIG[] PROGMEM = "<body> <div style=\"text-align:left;display:inline-block;min-width:260px;\"> <form action=\"/handleConfig\" method=\"POST\"> <h4 style=\"text-align: center;\">Password:</h4> <input type=\"password\" class=\"input_type\" name=\"passap1\" minlength=\"8\" maxlength=\"16\" placeholder=\"Password\" autofocus required><br><br> <h4 style=\"text-align: center;\">Confirm Password:</h4> <input type=\"password\" class=\"input_type\" name=\"passap2\" minlength=\"8\" maxlength=\"16\" placeholder=\"Confirm Password\" required><br><br> <input type=\"submit\" style=\"border:0;border-radius:0.3rem;background-color:#010012;color:#fff;line-height:2.4rem;font-size:1.2rem;width:100%;\" name=\"Submit\" value=\"Submit\"> </form> </div> </body> </html>";

const char HTTP_ROOT[] PROGMEM = "<body> <div style=\"text-align:left;display:inline-block;min-width:260px;\"> <form action=\"/wifiscan\" method=\"get\"><button>Connect to WiFi</button></form><br /> <form action=\"/manscan\" method=\"get\"><button>Connect to WiFi manually</button></form><br /> <form action=\"/ap_config\" method=\"get\"><button>Change Password</button></form><br /> <form action=\"/reset\" method=\"post\"><button>Reset</button></form><br /> </div> </body> </html>";

/*const char DEVICE_CONTROL[] PROGMEM ="<body> <div style=\"text-align:left;display:inline-block;min-width:260px;\"> <h4 style=\"text-align: center;\"> Device 1</h4> <div> <form action=\"/\" method=\"GET\"> <button name=\"D1\" style=\"@style1;\">@status1@</button> </form> <div>Timer: <form action=\"/\" method=\"POST\"> <input type=\"number\" name=\"timerD1h\" min=\"1\" max=\"20\" placeholder=\"hour(s)\"> <input type=\"number\" name=\"timerD1m\" min=\"1\" max=\"60\" placeholder=\"min(s)\"> <input type=\"submit\" value=\"Set Timer\"></form> </div> </div> <h4 style=\"text-align: center;\"> Device 2</h4> <div> <form action=\"/\" method=\"GET\"> <button name=\"D2\" style=\"@style2;\">@status2@</button> </form> <div>Timer: <form action=\"/\" method=\"POST\"> <input type=\"number\" name=\"timerD2h\" min=\"1\" max=\"20\" placeholder=\"hour(s)\"> <input type=\"number\" name=\"timerD2m\" min=\"1\" max=\"60\" placeholder=\"min(s)\"> <input type=\"submit\" value=\"Set Timer\"></form> </div> </div> <h4 style=\"text-align: center;\"> Device 3</h4> <div> <form action=\"/\" method=\"GET\"> <button name=\"D3\" style=\"@style3;\">@status3@</button> </form> <div>Timer: <form action=\"/\" method=\"POST\"> <input type=\"number\" name=\"timerD3h\" min=\"1\" max=\"20\" placeholder=\"hour(s)\"> <input type=\"number\" name=\"timerD3m\" min=\"1\" max=\"60\" placeholder=\"min(s)\"> <input type=\"submit\" value=\"Set Timer\"></form> </div> </div> <h4 style=\"text-align: center;\"> Device 4</h4> <div> <form action=\"/\" method=\"GET\"> <button name=\"D4\" style=\"@style4;\">@status4@</button> </form> <div>Timer: <form action=\"/\" method=\"POST\"> <input type=\"number\" name=\"timerD4h\" min=\"1\" max=\"20\" placeholder=\"hour(s)\"> <input type=\"number\" name=\"timerD4m\" min=\"1\" max=\"60\" placeholder=\"min(s)\"> <input type=\"submit\" value=\"Set Timer\"></form> </div> </div> </div> </body> </html>";*/

const char WIFI_AUTO_SCAN[] PROGMEM = "<body> <div style=\"text-align:left;display:inline-block;min-width:260px;\"> <div><a href=\"#\" onclick=\"copyIt(this)\">@SSID1@</a><span class=\"rssi\">@SIG1@</span></div> <div><a href=\"#\" onclick=\"copyIt(this)\">@SSID2@</a><span class=\"rssi\">@SIG2@</span></div> <div><a href=\"#\" onclick=\"copyIt(this)\">@SSID3@</a><span class=\"rssi\">@SIG3@ </span></div> <div><a href=\"#\" onclick=\"copyIt(this)\">@SSID4@</a><span class=\"rssi\">@SIG4@ </span></div> <div align=\"center\"> <form action=\"/handleConfig\" method=\"POST\"> <h4 style=\"text-align: center;\"> SSID:</h4> <input type=\"text\" id=\"ssid\" name=\"stassid\" minlength=\"8\" maxlength=\"32\" placeholder=\"SSID\" autofocus required><br><br> <h4 style=\"text-align: center;\"> Password:</h4> <input type=\"password\" name=\"stapass\" minlength=\"8\" maxlength=\"16\" placeholder=\"Password\" required><br><br> <input type=\"submit\" name=\"Submit\" value=\"Submit\"> </form> </div> </body> </html>";

#endif
